### PR TITLE
detail::path_base() now supports both path seperators on Windows.

### LINKED ISSUE #87: detail::path_base() doesn't handle Linux path separators on Windows
Was attempting to test whether a kernel with [GLM](https://github.com/g-truc/glm) would build with NVRTC (I'm not hopeful).

Ran into a failure, where all GLMs nested `#include` statements were failing to resolve.

````
glm/glm.hpp(105): warning: detail/_fixes.hpp: [jitify] File not found
glm/glm.hpp(107): warning: detail/setup.hpp: [jitify] File not found
glm/glm.hpp(114): warning: fwd.hpp: [jitify] File not found
glm/glm.hpp(116): warning: vec2.hpp: [jitify] File not found
glm/glm.hpp(117): warning: vec3.hpp: [jitify] File not found
glm/glm.hpp(118): warning: vec4.hpp: [jitify] File not found
glm/glm.hpp(119): warning: mat2x2.hpp: [jitify] File not found
glm/glm.hpp(120): warning: mat2x3.hpp: [jitify] File not found
glm/glm.hpp(121): warning: mat2x4.hpp: [jitify] File not found
glm/glm.hpp(122): warning: mat3x2.hpp: [jitify] File not found
glm/glm.hpp(123): warning: mat3x3.hpp: [jitify] File not found
glm/glm.hpp(124): warning: mat3x4.hpp: [jitify] File not found
glm/glm.hpp(125): warning: mat4x2.hpp: [jitify] File not found
glm/glm.hpp(126): warning: mat4x3.hpp: [jitify] File not found
glm/glm.hpp(127): warning: mat4x4.hpp: [jitify] File not found
etc
````

Added a breakpoint [here](https://github.com/NVIDIA/jitify/blob/2f65aa60c5ebabe28d254feb092e727a5a754a25/jitify.hpp#L2798) to catch where `detail::load_source()` was being called.

Found these variable values

```
include_parent_fullpath = "C:/Users/Robadob/fgpu2/build/FLAMEGPU2/_deps/flamegpu2_visualiser-build/glm-src\\glm/glm.hpp" (Note that's an escaped \, not double)
include_path = "C:/Users/Robadob/fgpu2/build/FLAMEGPU2/_deps/flamegpu2_visualiser-build/glm-src"
```

This means that `detail::path_base()` is handling the path improperly.

The method is fairly simple

```c++
inline std::string path_base(std::string p) {
  // "/usr/local/myfile.dat" -> "/usr/local"
  // "foo/bar"  -> "foo"
  // "foo/bar/" -> "foo/bar"
#if defined _WIN32 || defined _WIN64
  char sep = '\\';
#else
  char sep = '/';
#endif
  size_t i = p.find_last_of(sep);
  if (i != std::string::npos) {
    return p.substr(0, i);
  } else {
    return "";
  }
}
```

Seems quite clear that it's neglecting the fact that either path separator is supported under Windows (as far as I understand).

Should be an easy fix, I'll make a PR soon.

**Edit:** According to people on [StackOverflow](https://stackoverflow.com/a/5790259/1646387), MSVC used to require backslash, but now it doesn't care. Unclear when that requirement was lifted, regardless I don't expect it will affect NVRTC.

### PR DESCRIPTION
**Pull request by Robadob**
Have tested that it fixes the problem reported in #87.

`std::string;:npos` is the unsigned value of `-1`, so can't just use `std::max` without some nasty casting.

Closes #87

### CODE REVIEW

File: jitify.hpp [hunk 1]
```diff
@@ -365,11 +365,16 @@ inline std::string path_base(std::string p) {
   // "foo/bar"  -> "foo"
   // "foo/bar/" -> "foo/bar"
 #if defined _WIN32 || defined _WIN64
-  char sep = '\\';
+  size_t i = p.find_last_of('\\');
+  size_t j = p.find_last_of('/');
```
Comment (benbarsdell) [inline jitify.hpp:369]: I think this can be simplified by using the multi-character overload `find_last_of("\\/")`.

Comment (Robadob) [reply jitify.hpp:369]: That would make sense, I'll amend it later today.

**Comment by Robadob** [comment]
Wasn't aware of those overloads, have checked it still works. Much smaller of a change now.

**Review by benbarsdell — APPROVED** [review]
